"""
AgentCore Runtime Agent: returns_agent_runtime
Generated by AgentCore MCP Server

This agent is ready to deploy to AgentCore Runtime with:
1. BedrockAgentCoreApp entrypoint
2. Memory integration
3. Gateway tools
4. Knowledge Base access
5. All custom tools
6. Comprehensive error handling
"""

import os
import json
from bedrock_agentcore.runtime import BedrockAgentCoreApp
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import current_time, retrieve
from strands.tools.mcp import MCPClient
from mcp.client.streamable_http import streamablehttp_client
import requests
from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig, RetrievalConfig
from bedrock_agentcore.memory.integrations.strands.session_manager import AgentCoreMemorySessionManager
from datetime import datetime
import traceback

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Initialize app
app = BedrockAgentCoreApp()

print("="*80)
print("AGENTCORE RUNTIME AGENT: returns_agent_runtime")
print("="*80)
print("Initializing...")

# ============================================================================
# CUSTOM TOOL DEFINITIONS
# ============================================================================

@tool
def check_return_eligibility(purchase_date: str, category: str) -> str:
    """Check if an item is eligible for return.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (e.g., 'electronics', 'clothing', 'books')
    """
    try:
        purchase = datetime.strptime(purchase_date, '%Y-%m-%d')
        days_since_purchase = (datetime.now() - purchase).days
        
        # Return windows by category
        return_windows = {
            'electronics': 30,
            'clothing': 30,
            'books': 30,
            'jewelry': 30,
            'grocery': 30,
            'default': 30
        }
        
        window = return_windows.get(category.lower(), return_windows['default'])
        
        if days_since_purchase <= window:
            days_remaining = window - days_since_purchase
            return f"✓ Eligible for return. You have {days_remaining} days remaining in your {window}-day return window."
        else:
            days_over = days_since_purchase - window
            return f"✗ Not eligible. The {window}-day return window closed {days_over} days ago."
    except ValueError:
        return "Error: Invalid date format. Please use YYYY-MM-DD format."
    except Exception as e:
        return f"Error checking eligibility: {str(e)}"

@tool
def calculate_refund_amount(original_price: float, condition: str, return_reason: str) -> str:
    """Calculate the refund amount for a return.
    
    Args:
        original_price: Original purchase price in dollars
        condition: Item condition ('unopened', 'opened', 'used', 'damaged')
        return_reason: Reason for return ('defective', 'wrong_item', 'changed_mind', 'other')
    """
    try:
        refund_percentage = 1.0
        
        # Adjust based on condition
        condition_adjustments = {
            'unopened': 1.0,
            'opened': 0.9,
            'used': 0.7,
            'damaged': 0.5
        }
        
        # Adjust based on reason
        reason_adjustments = {
            'defective': 1.0,
            'wrong_item': 1.0,
            'changed_mind': 0.85,
            'other': 0.85
        }
        
        condition_factor = condition_adjustments.get(condition.lower(), 0.7)
        reason_factor = reason_adjustments.get(return_reason.lower(), 0.85)
        
        # For defective/wrong items, ignore condition penalty
        if return_reason.lower() in ['defective', 'wrong_item']:
            refund_percentage = 1.0
        else:
            refund_percentage = condition_factor * reason_factor
        
        refund_amount = original_price * refund_percentage
        restocking_fee = original_price - refund_amount
        
        result = f"Refund Calculation:\n"
        result += f"Original Price: ${original_price:.2f}\n"
        result += f"Condition: {condition} ({int(condition_factor*100)}%)\n"
        result += f"Reason: {return_reason} ({int(reason_factor*100)}%)\n"
        result += f"Refund Amount: ${refund_amount:.2f}\n"
        
        if restocking_fee > 0:
            result += f"Restocking Fee: ${restocking_fee:.2f}"
        
        return result
    except Exception as e:
        return f"Error calculating refund: {str(e)}"

@tool
def format_policy_response(policy_text: str, customer_question: str) -> str:
    """Format policy information in a customer-friendly way.
    
    Args:
        policy_text: Raw policy text from knowledge base
        customer_question: The customer's original question
    """
    try:
        # Add friendly formatting
        formatted = "📋 Policy Information:\n\n"
        formatted += f"Regarding your question: '{customer_question}'\n\n"
        formatted += policy_text
        formatted += "\n\n💡 Need more help? Feel free to ask follow-up questions!"
        
        return formatted
    except Exception as e:
        return f"Error formatting policy: {str(e)}"

# ============================================================================
# GATEWAY HELPER FUNCTIONS
# ============================================================================

def get_cognito_token_with_scope(client_id, client_secret, discovery_url, scope):
    """Get Cognito bearer token with a specific OAuth scope"""
    try:
        # Extract token endpoint from discovery URL
        discovery_response = requests.get(discovery_url, timeout=10)
        discovery_response.raise_for_status()
        token_endpoint = discovery_response.json()['token_endpoint']
        
        # Get token using client credentials flow
        response = requests.post(
            token_endpoint,
            data={
                'grant_type': 'client_credentials',
                'client_id': client_id,
                'client_secret': client_secret,
                'scope': scope
            },
            headers={'Content-Type': 'application/x-www-form-urlencoded'},
            timeout=10
        )
        
        response.raise_for_status()
        return response.json()["access_token"]
    except Exception as e:
        print(f"Error getting Cognito token: {e}")
        raise

def create_mcp_client():
    """Create MCP client for gateway access"""
    try:
        # Get environment variables
        gateway_url = os.environ.get("GATEWAY_URL")
        cognito_client_id = os.environ.get("COGNITO_CLIENT_ID")
        cognito_client_secret = os.environ.get("COGNITO_CLIENT_SECRET")
        cognito_discovery_url = os.environ.get("COGNITO_DISCOVERY_URL")
        oauth_scopes = os.environ.get("OAUTH_SCOPES", "gateway-api/read gateway-api/write")
        
        if not all([gateway_url, cognito_client_id, cognito_client_secret, cognito_discovery_url]):
            print("Warning: Gateway environment variables not set - gateway tools will not be available")
            return None
        
        token = get_cognito_token_with_scope(
            cognito_client_id,
            cognito_client_secret,
            cognito_discovery_url,
            oauth_scopes
        )
        
        print(f"✓ Gateway configured: {gateway_url}")
        return MCPClient(
            lambda: streamablehttp_client(
                gateway_url,
                headers={"Authorization": f"Bearer {token}"},
            )
        )
    except Exception as e:
        print(f"Warning: Failed to create MCP client: {e}")
        return None

# ============================================================================
# RUNTIME ENTRYPOINT
# ============================================================================

@app.entrypoint
def invoke(payload, context=None):
    """AgentCore Runtime entrypoint with comprehensive error handling"""
    try:
        print("\n" + "="*80)
        print("AGENT INVOCATION")
        print("="*80)
        
        # Initialize model
        bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)
        print(f"✓ Model initialized: {MODEL_ID}")
        
        # Get environment variables
        memory_id = os.environ.get("MEMORY_ID")
        kb_id = os.environ.get("KNOWLEDGE_BASE_ID")
        
        if not memory_id:
            error_msg = "Error: MEMORY_ID environment variable is required"
            print(f"✗ {error_msg}")
            return error_msg
        
        print(f"✓ Memory ID: {memory_id}")
        if kb_id:
            print(f"✓ Knowledge Base ID: {kb_id}")
        
        # Extract session and actor info
        session_id = context.session_id if context else SESSION_ID
        actor_id = payload.get("actor_id", ACTOR_ID)
        print(f"✓ Session ID: {session_id}")
        print(f"✓ Actor ID: {actor_id}")
        
        # Configure memory with retrieval settings
        agentcore_memory_config = AgentCoreMemoryConfig(
            memory_id=memory_id,
            session_id=session_id,
            actor_id=actor_id,
            retrieval_config={
                f"app/{actor_id}/semantic": RetrievalConfig(top_k=3),
                f"app/{actor_id}/preferences": RetrievalConfig(top_k=3),
                f"app/{actor_id}/{session_id}/summary": RetrievalConfig(top_k=2),
            }
        )
        
        session_manager = AgentCoreMemorySessionManager(
            agentcore_memory_config=agentcore_memory_config,
            region_name=REGION
        )
        print("✓ Memory session manager configured")
        
        # Build system prompt with KB info
        if kb_id:
            system_prompt = f"""Production returns assistant with full memory and gateway capabilities. Use the retrieve tool to access Amazon return policy documents for accurate information.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query

You have access to:
- Gateway tools for external operations
- Customer conversation history and preferences through memory
- Knowledge base for policy information"""
        else:
            system_prompt = """Production returns assistant with full memory and gateway capabilities.

You have access to:
- Gateway tools for external operations
- Customer conversation history and preferences through memory"""
        
        # Build custom tools list
        custom_tools = [current_time, check_return_eligibility, calculate_refund_amount, format_policy_response]
        
        # Add retrieve tool if KB is configured
        if kb_id:
            custom_tools.append(retrieve)
            print("✓ Knowledge Base retrieve tool added")
        
        # Try to create MCP client for gateway tools
        mcp_client = create_mcp_client()
        
        if mcp_client:
            try:
                # Keep MCP client active during agent execution
                with mcp_client:
                    # Get gateway tools from MCP client
                    gateway_tools = list(mcp_client.list_tools_sync())
                    print(f"✓ Loaded {len(gateway_tools)} gateway tool(s)")
                    
                    # Create agent with all tools
                    agent = Agent(
                        model=bedrock_model,
                        tools=custom_tools + gateway_tools,
                        system_prompt=system_prompt,
                        session_manager=session_manager
                    )
                    
                    user_input = payload.get("prompt", "")
                    print(f"\nUser input: {user_input}")
                    print("\nProcessing...")
                    
                    response = agent(user_input)
                    result = response.message["content"][0]["text"]
                    
                    print("\n✓ Agent response generated")
                    print("="*80)
                    return result
            except Exception as e:
                print(f"Warning: Failed to use gateway tools: {e}")
                print("Falling back to agent without gateway tools")
                traceback.print_exc()
        
        # Create agent without gateway tools (fallback)
        print("✓ Creating agent without gateway tools")
        agent = Agent(
            model=bedrock_model,
            tools=custom_tools,
            system_prompt=system_prompt,
            session_manager=session_manager
        )
        
        user_input = payload.get("prompt", "")
        print(f"\nUser input: {user_input}")
        print("\nProcessing...")
        
        response = agent(user_input)
        result = response.message["content"][0]["text"]
        
        print("\n✓ Agent response generated")
        print("="*80)
        return result
    
    except Exception as e:
        error_msg = f"Agent invocation failed: {str(e)}"
        print(f"\n✗ {error_msg}")
        traceback.print_exc()
        print("="*80)
        return error_msg

if __name__ == "__main__":
    print("✓ Agent initialized and ready for deployment")
    print("="*80)
    app.run()
