"""
Standalone Strands Agent: returns_refunds_agent
Generated by AgentCore MCP Server

Integrations:
- Memory: Disabled
- Gateway: Disabled
- Knowledge Base: Enabled
"""

import os
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from datetime import datetime

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Model configuration
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)

# ============================================================================
# KNOWLEDGE BASE CONFIGURATION
# ============================================================================

kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "YOUR_KB_ID_HERE")
print(f"✓ Knowledge Base ID: {kb_id}")

# System prompt
system_prompt = f"""You are a helpful returns and refunds assistant. Help customers check return eligibility, calculate refunds, and understand policies. Use the retrieve tool to access Amazon return policy documents for accurate information. Be friendly and accurate.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query"""

# Custom tool definitions

@tool
def check_return_eligibility(purchase_date: str, category: str) -> str:
    """Check if an item is eligible for return.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (e.g., 'electronics', 'clothing', 'books')
    """
    try:
        purchase = datetime.strptime(purchase_date, '%Y-%m-%d')
        days_since_purchase = (datetime.now() - purchase).days
        
        # Return windows by category
        return_windows = {
            'electronics': 30,
            'clothing': 30,
            'books': 30,
            'jewelry': 30,
            'grocery': 30,
            'default': 30
        }
        
        window = return_windows.get(category.lower(), return_windows['default'])
        
        if days_since_purchase <= window:
            days_remaining = window - days_since_purchase
            return f"✓ Eligible for return. You have {days_remaining} days remaining in your {window}-day return window."
        else:
            days_over = days_since_purchase - window
            return f"✗ Not eligible. The {window}-day return window closed {days_over} days ago."
    except ValueError:
        return "Error: Invalid date format. Please use YYYY-MM-DD format."

@tool
def calculate_refund_amount(original_price: float, condition: str, return_reason: str) -> str:
    """Calculate the refund amount for a return.
    
    Args:
        original_price: Original purchase price in dollars
        condition: Item condition ('unopened', 'opened', 'used', 'damaged')
        return_reason: Reason for return ('defective', 'wrong_item', 'changed_mind', 'other')
    """
    refund_percentage = 1.0
    
    # Adjust based on condition
    condition_adjustments = {
        'unopened': 1.0,
        'opened': 0.9,
        'used': 0.7,
        'damaged': 0.5
    }
    
    # Adjust based on reason
    reason_adjustments = {
        'defective': 1.0,
        'wrong_item': 1.0,
        'changed_mind': 0.85,
        'other': 0.85
    }
    
    condition_factor = condition_adjustments.get(condition.lower(), 0.7)
    reason_factor = reason_adjustments.get(return_reason.lower(), 0.85)
    
    # For defective/wrong items, ignore condition penalty
    if return_reason.lower() in ['defective', 'wrong_item']:
        refund_percentage = 1.0
    else:
        refund_percentage = condition_factor * reason_factor
    
    refund_amount = original_price * refund_percentage
    restocking_fee = original_price - refund_amount
    
    result = f"Refund Calculation:\n"
    result += f"Original Price: ${original_price:.2f}\n"
    result += f"Condition: {condition} ({int(condition_factor*100)}%)\n"
    result += f"Reason: {return_reason} ({int(reason_factor*100)}%)\n"
    result += f"Refund Amount: ${refund_amount:.2f}\n"
    
    if restocking_fee > 0:
        result += f"Restocking Fee: ${restocking_fee:.2f}"
    
    return result

@tool
def format_policy_response(policy_text: str, customer_question: str) -> str:
    """Format policy information in a customer-friendly way.
    
    Args:
        policy_text: Raw policy text from knowledge base
        customer_question: The customer's original question
    """
    # Add friendly formatting
    formatted = "📋 Policy Information:\n\n"
    formatted += f"Regarding your question: '{customer_question}'\n\n"
    formatted += policy_text
    formatted += "\n\n💡 Need more help? Feel free to ask follow-up questions!"
    
    return formatted


def run_agent(user_input: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Run the agent with user input"""
    
    # Build tools list
    custom_tools = [retrieve, current_time, check_return_eligibility, calculate_refund_amount, format_policy_response]
    
    # Create agent
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]

if __name__ == "__main__":
    # Example usage
    user_query = "Hello, how can you help me?"
    result = run_agent(user_query)
    print("\n" + "="*80)
    print("AGENT RESPONSE:")
    print("="*80)
    print(result)
